#!/bin/bash

# who the fuck needs loops?

set -e

POSTGRES="psql --username ${POSTGRES_USER}"

$POSTGRES <<-EOSQL
CREATE ROLE $COURSES_USER PASSWORD '$COURSES_PASS' CREATEDB CREATEROLE INHERIT LOGIN;
EOSQL

$POSTGRES <<-EOSQL
CREATE ROLE $AUTH_USER PASSWORD '$AUTH_PASS' CREATEDB CREATEROLE INHERIT LOGIN;
EOSQL

$POSTGRES <<-EOSQL
CREATE ROLE $GITEA_EXERCISES_USER PASSWORD '$GITEA_EXERCISES_PASS' CREATEDB CREATEROLE INHERIT LOGIN;
EOSQL

$POSTGRES <<-EOSQL
CREATE ROLE $GITEA_EXAMS_USER PASSWORD '$GITEA_EXAMS_PASS' CREATEDB CREATEROLE INHERIT LOGIN;
EOSQL

$POSTGRES <<-EOSQL
CREATE ROLE $BUILD_USER PASSWORD '$BUILD_PASS' CREATEDB CREATEROLE INHERIT LOGIN;
EOSQL

$POSTGRES <<EOSQL
CREATE DATABASE $COURSES_USER OWNER $COURSES_USER;
EOSQL

$POSTGRES <<EOSQL
CREATE DATABASE $AUTH_USER OWNER $AUTH_USER;
EOSQL

$POSTGRES <<EOSQL
CREATE DATABASE $GITEA_EXERCISES_USER OWNER $GITEA_EXERCISES_USER;
EOSQL

$POSTGRES <<EOSQL
CREATE DATABASE $GITEA_EXAMS_USER OWNER $GITEA_EXAMS_USER;
EOSQL

$POSTGRES <<EOSQL
CREATE DATABASE $BUILD_USER OWNER $BUILD_USER;
EOSQL
